export enum Action {

    GET_ALL_PLAYERS_ACTION = "GET_STAT",
    GET_ALL_PLAYERS_RESPONSE = "GET_STAT_RESPONSE",
    AUTHENTICATE__RESPONSE = "AUTHENTICATE_RESPONSE",
    AUTHENTICATE = "AUTHENTICATE",
    GET_MAPPING_CONFIGURATION_RESPONSE = "GET_MAPPING_CONFIGURATION_RESPONSE"


}
