/**
 * The List of possible action that can occure between the client and the server.
 */
export enum Action {

    GET_ALL_STATS = "GET_ALL_STATS",
    GET_ALL_STATS_RESPONSE = "GET_ALL_STATS_RESPONSE",
    AUTHENTICATE = "AUTHENTICATE",
    AUTHENTICATE_RESPONSE = "AUTHENTICATE_RESPONSE",
    SET_MAX_HEALTH = "SET_MAX_HEALTH",
    SET_MAX_HEALTH_RESPONSE = "SET_MAX_HEALTH_RESPONSE",
    GET_MAPPING_CONFIGURATION_RESPONSE = "GET_MAPPING_CONFIGURATION_RESPONSE",
    INTERNAL_ERROR = "INTERNAL_ERROR"

}
